/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Clases.Banco;
import Clases.Cliente;
/**
 *
 * @author Tayle
 */
public class AgregarCuenta extends javax.swing.JFrame {

    private final Cliente cliente;
    private final Banco banco;
    /**
     * Creates new form AgregarCuenta
     */
    public AgregarCuenta(Cliente cliente, Banco banco) {
        initComponents();
        this.cliente = cliente;
        this.banco = banco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cancelar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        LabelPin = new javax.swing.JLabel();
        LabelSaldo = new javax.swing.JLabel();
        LabelNumero = new javax.swing.JLabel();
        txtnumeroCuenta = new javax.swing.JTextField();
        txtSaldoInicial = new javax.swing.JTextField();
        txtPinCuenta = new javax.swing.JPasswordField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cancelar.setBackground(new java.awt.Color(0, 0, 51));
        Cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("Cancelar");
        Cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        Agregar.setBackground(new java.awt.Color(0, 0, 51));
        Agregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setText("Agregar cuenta");
        Agregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        LabelPin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelPin.setForeground(new java.awt.Color(255, 255, 255));
        LabelPin.setText("Pin :");
        getContentPane().add(LabelPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        LabelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSaldo.setForeground(new java.awt.Color(255, 255, 255));
        LabelSaldo.setText("Saldo inicial :");
        getContentPane().add(LabelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        LabelNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        LabelNumero.setText("Numero de cuenta :");
        getContentPane().add(LabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtnumeroCuenta.setBackground(new java.awt.Color(0, 0, 51));
        txtnumeroCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtnumeroCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnumeroCuenta.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtnumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 120, -1));

        txtSaldoInicial.setBackground(new java.awt.Color(0, 0, 51));
        txtSaldoInicial.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldoInicial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSaldoInicial.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, -1));

        txtPinCuenta.setBackground(new java.awt.Color(0, 0, 51));
        txtPinCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtPinCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPinCuenta.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPinCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpeg"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Banco banco = new Banco();
                banco.cargarClientes("clentes.xml");
                new AgregarCuenta(null, banco).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelPin;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JPasswordField txtPinCuenta;
    private javax.swing.JTextField txtSaldoInicial;
    private javax.swing.JTextField txtnumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
