/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Cajero;

/**
 *
 * @author Maikel
 */
public class ConsultarTipoDeCambio extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarTipoDeCambio
     */
    public ConsultarTipoDeCambio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Compra1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Venta = new javax.swing.JLabel();
        Compra2 = new javax.swing.JLabel();
        Compras = new javax.swing.JTextField();
        Ventas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        Compra1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Compra1.setForeground(new java.awt.Color(255, 255, 255));
        Compra1.setText("Compra de dolares");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Tipo de cambio en dolares");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 30));

        Venta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Venta.setForeground(new java.awt.Color(255, 255, 255));
        Venta.setText("Venta de dolares");
        getContentPane().add(Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, 20));

        Compra2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Compra2.setForeground(new java.awt.Color(255, 255, 255));
        Compra2.setText("Compra de dolares");
        getContentPane().add(Compra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, -1));

        Compras.setBackground(new java.awt.Color(0, 0, 102));
        Compras.setForeground(new java.awt.Color(255, 255, 255));
        Compras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Compras.setCaretColor(new java.awt.Color(255, 255, 255));
        Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprasActionPerformed(evt);
            }
        });
        getContentPane().add(Compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, -1));

        Ventas.setBackground(new java.awt.Color(0, 0, 102));
        Ventas.setForeground(new java.awt.Color(255, 255, 255));
        Ventas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Ventas.setCaretColor(new java.awt.Color(255, 255, 255));
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        getContentPane().add(Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 300, 430));

        pack();
    }// </editor-fold>                        

    private void ComprasActionPerformed(java.awt.event.ActionEvent evt) {                                        
       String Text=Cajero.consultarTipoCambio("compra");
       jLabel1.setText(Text);
    }                                       

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {                                       
       String Text=Cajero.consultarTipoCambio("venta");
       jLabel1.setText(Text);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarTipoDeCambio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Compra1;
    private javax.swing.JLabel Compra2;
    private javax.swing.JTextField Compras;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Venta;
    private javax.swing.JTextField Ventas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
