/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Banco;
import Clases.Cliente;
import Clases.Cuenta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.FlowLayout;
/**
 *
 * @author Tayle
 */
public class InterfazCliente extends javax.swing.JFrame {

    private final Banco banco;
    private final Cliente cliente;
    private final String idUsuario;

    public InterfazCliente(Banco banco, Cliente cliente, String id) {
        initComponents();
        this.idUsuario = id;
        this.banco = banco;
        this.cliente = cliente;
        cargarCuentas();
    }

    private String encontrarClientePorID(){
        for (Cliente cliente : banco.getClientes()) {
            if (cliente.getIdentificacion().equals(idUsuario)) {
                String clienteId = cliente.getIdentificacion();
                return clienteId;
            }
        }
        return "0";
    }
    
    private Cliente obtenerCliente(){
        Cliente clienteEncontrado = null;
        for (Cliente cliente : banco.getClientes()) {
            if (cliente.getIdentificacion().equals(idUsuario)) {
                clienteEncontrado = cliente;
                return clienteEncontrado;
            }
        }
        return null;
    }

    private void cargarCuentas() {
        banco.cargarClientes("clientes.xml");
        // Limpiar el contenido del PanelCuentas antes de añadir los elementos.
        PanelCuentas.removeAll();

        // Si el cliente no tiene cuentas, mostrar un mensaje.
        if (cliente.getCuentas().isEmpty()) {
            JLabel labelSinCuentas = new JLabel("¡No posees ninguna cuenta!");
            labelSinCuentas.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
            labelSinCuentas.setForeground(java.awt.Color.BLACK);
            labelSinCuentas.setHorizontalAlignment(JLabel.CENTER);
            PanelCuentas.setLayout(new java.awt.FlowLayout(FlowLayout.CENTER));
            PanelCuentas.add(labelSinCuentas);
        } else {
            int yPosition = 20; // Posición inicial para colocar los botones.

            // Iterar por cada cuenta del cliente.
            for (Cuenta cuenta : cliente.getCuentas()) {
                JButton botonCuenta = new JButton("Cuenta: " + cuenta.getNumeroCuenta());
                botonCuenta.setBounds(20, yPosition, 200, 30);
                yPosition += 40; // Espacio entre botones.

                // Añadir ActionListener a cada botón.
                botonCuenta.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JLabel labelDetalles = new JLabel("Has seleccionado la cuenta: " + cuenta.getNumeroCuenta());
                        PanelCuentas.add(labelDetalles);
                        PanelCuentas.revalidate();
                        PanelCuentas.repaint();
                    }
                });
                PanelCuentas.add(botonCuenta); 
            }
        }
        // Refrescar el PanelCuentas para mostrar los cambios.
        PanelCuentas.revalidate();
        PanelCuentas.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameCuentas = new javax.swing.JInternalFrame();
        PanelCuentas = new javax.swing.JPanel();
        ScrollBarCuentas = new javax.swing.JScrollBar();
        EliminarCuenta = new javax.swing.JButton();
        AgregarCuenta = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        Configuracion = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameCuentas.setBackground(new java.awt.Color(0, 0, 0));
        FrameCuentas.setBorder(null);
        FrameCuentas.setForeground(new java.awt.Color(255, 255, 255));
        FrameCuentas.setTitle("Cuentas del cliente");
        FrameCuentas.setVisible(true);

        PanelCuentas.setPreferredSize(new java.awt.Dimension(392, 300));

        javax.swing.GroupLayout PanelCuentasLayout = new javax.swing.GroupLayout(PanelCuentas);
        PanelCuentas.setLayout(PanelCuentasLayout);
        PanelCuentasLayout.setHorizontalGroup(
            PanelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCuentasLayout.createSequentialGroup()
                .addContainerGap(527, Short.MAX_VALUE)
                .addComponent(ScrollBarCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelCuentasLayout.setVerticalGroup(
            PanelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollBarCuentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FrameCuentasLayout = new javax.swing.GroupLayout(FrameCuentas.getContentPane());
        FrameCuentas.getContentPane().setLayout(FrameCuentasLayout);
        FrameCuentasLayout.setHorizontalGroup(
            FrameCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameCuentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        FrameCuentasLayout.setVerticalGroup(
            FrameCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCuentasLayout.createSequentialGroup()
                .addComponent(PanelCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(FrameCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 560, 370));

        EliminarCuenta.setBackground(new java.awt.Color(0, 0, 51));
        EliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCuenta.setText("Eliminar Cuenta");
        getContentPane().add(EliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        AgregarCuenta.setBackground(new java.awt.Color(0, 0, 51));
        AgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCuenta.setText("Agregar Cuenta");
        AgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        BotonVolver.setBackground(new java.awt.Color(0, 0, 102));
        BotonVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonVolver.setForeground(new java.awt.Color(255, 255, 255));
        BotonVolver.setText("Cerrar sesión");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Configuracion.setBackground(new java.awt.Color(0, 0, 51));
        Configuracion.setForeground(new java.awt.Color(255, 255, 255));
        Configuracion.setText("Configuración");
        Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(Configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpeg"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCuentaActionPerformed

    private void ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        this.dispose();
        MenuPrincipal referencia = new MenuPrincipal(banco);
        IniciarSesion ventana = new IniciarSesion(referencia);
        referencia.setVisible(true);
    }//GEN-LAST:event_BotonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Banco banco = new Banco();
            banco.cargarClientes("clientes.xml");
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCuenta;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JButton Configuracion;
    private javax.swing.JButton EliminarCuenta;
    private javax.swing.JInternalFrame FrameCuentas;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JPanel PanelCuentas;
    private javax.swing.JScrollBar ScrollBarCuentas;
    // End of variables declaration//GEN-END:variables
}
