/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Banco;
import Clases.Cliente;
import Clases.Cuenta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Tayle
 */
public class InterfazCliente extends javax.swing.JFrame {

    private final Banco banco;
    private final Cliente cliente;
    private final String idUsuario;

    public InterfazCliente(Banco banco, Cliente cliente, String idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;
        this.banco = banco;
        this.cliente = cliente;
        cargarCuentas();
    }

    private void cargarCuentas() {
        banco.cargarClientes("clientes.xml");
        // Limpiar el contenido del PanelCuentas antes de añadir los elementos.
        PanelCuentas.removeAll();

        // Si el cliente no tiene cuentas, mostrar un mensaje.
        if (cliente.getCuentas().isEmpty()) {
            JLabel labelSinCuentas = new JLabel("¡No posees ninguna cuenta!");
            PanelCuentas.add(labelSinCuentas); // Añadir al PanelCuentas
        } else {
            int yPosition = 20; // Posición inicial para colocar los botones.

            // Iterar por cada cuenta del cliente.
            for (Cuenta cuenta : cliente.getCuentas()) {
                JButton botonCuenta = new JButton("Cuenta: " + cuenta.getNumeroCuenta());
                botonCuenta.setBounds(20, yPosition, 200, 30);
                yPosition += 40; // Espacio entre botones.

                // Añadimos ActionListener a cada botón.
                botonCuenta.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JLabel labelDetalles = new JLabel("Has seleccionado la cuenta: " + cuenta.getNumeroCuenta());
                        PanelCuentas.add(labelDetalles);
                        PanelCuentas.revalidate();
                        PanelCuentas.repaint();
                    }
                });
                PanelCuentas.add(botonCuenta); 
            }
        }

        // Refrescamos el PanelCuentas para mostrar los cambios.
        PanelCuentas.revalidate();
        PanelCuentas.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameCuentas = new javax.swing.JInternalFrame();
        ScrollBarCuentas = new javax.swing.JScrollBar();
        PanelCuentas = new javax.swing.JPanel();
        EliminarCuenta = new javax.swing.JButton();
        AgregarCuenta = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        Configuracion = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameCuentas.setBackground(new java.awt.Color(0, 0, 0));
        FrameCuentas.setBorder(null);
        FrameCuentas.setForeground(new java.awt.Color(255, 255, 255));
        FrameCuentas.setTitle("Cuentas del cliente");
        FrameCuentas.setVisible(true);

        PanelCuentas.setPreferredSize(new java.awt.Dimension(392, 300));

        javax.swing.GroupLayout PanelCuentasLayout = new javax.swing.GroupLayout(PanelCuentas);
        PanelCuentas.setLayout(PanelCuentasLayout);
        PanelCuentasLayout.setHorizontalGroup(
            PanelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        PanelCuentasLayout.setVerticalGroup(
            PanelCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FrameCuentasLayout = new javax.swing.GroupLayout(FrameCuentas.getContentPane());
        FrameCuentas.getContentPane().setLayout(FrameCuentasLayout);
        FrameCuentasLayout.setHorizontalGroup(
            FrameCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameCuentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollBarCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        FrameCuentasLayout.setVerticalGroup(
            FrameCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCuentasLayout.createSequentialGroup()
                .addGroup(FrameCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(ScrollBarCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(FrameCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 560, 370));

        EliminarCuenta.setBackground(new java.awt.Color(0, 0, 51));
        EliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCuenta.setText("Eliminar Cuenta");
        getContentPane().add(EliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        AgregarCuenta.setBackground(new java.awt.Color(0, 0, 51));
        AgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCuenta.setText("Agregar Cuenta");
        AgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        BotonVolver.setBackground(new java.awt.Color(0, 0, 102));
        BotonVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonVolver.setForeground(new java.awt.Color(255, 255, 255));
        BotonVolver.setText("Volver");
        getContentPane().add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Configuracion.setBackground(new java.awt.Color(0, 0, 51));
        Configuracion.setForeground(new java.awt.Color(255, 255, 255));
        Configuracion.setText("Configuración");
        Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(Configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpeg"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCuentaActionPerformed

    private void ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Banco banco = new Banco();
                banco.cargarClientes("clientes.xml");
                
                String idUsuario = "1";

                // Busca al cliente por la identificación
                Cliente cliente = banco.buscarClientePorID(idUsuario);

                if (cliente != null) {
                    // Si el cliente se encuentra, obtenemos su identificación y cargamos la interfaz.
                    String identificacion = cliente.getIdentificacion();
                    new InterfazCliente(banco, cliente, identificacion).setVisible(true);
                } else {
                    System.out.println("Cliente no encontrado.");
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCuenta;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JButton Configuracion;
    private javax.swing.JButton EliminarCuenta;
    private javax.swing.JInternalFrame FrameCuentas;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JPanel PanelCuentas;
    private javax.swing.JScrollBar ScrollBarCuentas;
    // End of variables declaration//GEN-END:variables
}
