/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Tayle
 */
public class InterfazInfoCuenta extends javax.swing.JFrame {

    /**
     * Creates new form interfazInfoCuenta
     */
    public InterfazInfoCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CambiarPin = new javax.swing.JButton();
        RetirarColones = new javax.swing.JButton();
        DepositarColones = new javax.swing.JButton();
        DepositarDolares = new javax.swing.JButton();
        RetirarDolares = new javax.swing.JButton();
        RealizarTransferencia = new javax.swing.JButton();
        ConsultarTransferencias = new javax.swing.JButton();
        ConsultarCompra = new javax.swing.JButton();
        ConsultarVenta = new javax.swing.JButton();
        ConsultarSaldo = new javax.swing.JButton();
        ConsultarEstado = new javax.swing.JButton();
        ConsultarSaldoExtranjero = new javax.swing.JButton();
        LabelContenedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(0, 0, 51));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel1.setBackground(new java.awt.Color(1, 95, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 330, 550));

        CambiarPin.setText("Cambiar pin");
        getContentPane().add(CambiarPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 110, -1));

        RetirarColones.setText("Retiro en colones");
        RetirarColones.setPreferredSize(new java.awt.Dimension(137, 23));
        getContentPane().add(RetirarColones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 170, -1));

        DepositarColones.setText("Deposito en colones");
        getContentPane().add(DepositarColones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        DepositarDolares.setText("Deposito en dolares");
        getContentPane().add(DepositarDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        RetirarDolares.setText("Retiro en dolares");
        getContentPane().add(RetirarDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));

        RealizarTransferencia.setText("Realizar transferencia");
        getContentPane().add(RealizarTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        ConsultarTransferencias.setText("Consultar transacciones");
        getContentPane().add(ConsultarTransferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        ConsultarCompra.setText("Consultar compra");
        getContentPane().add(ConsultarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        ConsultarVenta.setText("Consultar venta");
        getContentPane().add(ConsultarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, -1));

        ConsultarSaldo.setText("Consultar saldo");
        getContentPane().add(ConsultarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        ConsultarEstado.setText("Consultar estado de cuenta");
        getContentPane().add(ConsultarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 220, -1));

        ConsultarSaldoExtranjero.setText("Consultar saldo en divisa extranjera");
        ConsultarSaldoExtranjero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarSaldoExtranjeroActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarSaldoExtranjero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 220, -1));

        LabelContenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo Redimensionado.jpeg"))); // NOI18N
        LabelContenedor.setPreferredSize(new java.awt.Dimension(100, 550));
        getContentPane().add(LabelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarSaldoExtranjeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarSaldoExtranjeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarSaldoExtranjeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInfoCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarPin;
    private javax.swing.JButton ConsultarCompra;
    private javax.swing.JButton ConsultarEstado;
    private javax.swing.JButton ConsultarSaldo;
    private javax.swing.JButton ConsultarSaldoExtranjero;
    private javax.swing.JButton ConsultarTransferencias;
    private javax.swing.JButton ConsultarVenta;
    private javax.swing.JButton DepositarColones;
    private javax.swing.JButton DepositarDolares;
    private javax.swing.JLabel LabelContenedor;
    private javax.swing.JButton RealizarTransferencia;
    private javax.swing.JButton RetirarColones;
    private javax.swing.JButton RetirarDolares;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
