/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Banco;
import Clases.Cliente;
import Clases.Cuenta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Tayle
 */
public class InterfazCliente extends javax.swing.JFrame {

    private final Banco banco;
    private final Cliente cliente;
    private final String idUsuario;

    public InterfazCliente(Banco banco, Cliente cliente, String idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;
        this.banco = banco;
        this.cliente = cliente;
        cargarCuentas();
    }

    private void cargarCuentas() {
        banco.cargarClientes("clientes.xml");
        // Limpiamos el contenido del FrameCuentas antes de añadir los elementos.
        FrameCuentas.getContentPane().removeAll();

        // Si el cliente no tiene cuentas, mostramos un mensaje.
        if (cliente.getCuentas().isEmpty()) {
            JLabel labelSinCuentas = new JLabel("¡No posees ninguna cuenta!");
            FrameCuentas.getContentPane().add(labelSinCuentas);
        } else {
            int yPosition = 20; // Posición inicial para colocar los botones.
            
            // Iteramos por cada cuenta del cliente.
            for (Cuenta cuenta : cliente.getCuentas()) {
                JButton botonCuenta = new JButton("Cuenta: " + cuenta.getNumeroCuenta());
                botonCuenta.setBounds(20, yPosition, 200, 30);
                yPosition += 40; // Espacio entre botones.

                // Añadimos ActionListener a cada botón.
                botonCuenta.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Aquí abres la ventana con los detalles de la cuenta seleccionada.
                        JLabel labelSinCuentas = new JLabel("Sin dudas que seleccionaste una cuenta eh!");
                        FrameCuentas.getContentPane().add(labelSinCuentas);
                    }
                });
                
                // Añadimos el botón al FrameCuentas.
                FrameCuentas.getContentPane().add(botonCuenta);
            }
        }

        // Refrescamos el Frame para mostrar los cambios.
        FrameCuentas.revalidate();
        FrameCuentas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameCuentas = new javax.swing.JInternalFrame();
        ScrollBarCuentas = new javax.swing.JScrollBar();
        BotonVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameCuentas.setVisible(true);

        javax.swing.GroupLayout FrameCuentasLayout = new javax.swing.GroupLayout(FrameCuentas.getContentPane());
        FrameCuentas.getContentPane().setLayout(FrameCuentasLayout);
        FrameCuentasLayout.setHorizontalGroup(
            FrameCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameCuentasLayout.createSequentialGroup()
                .addGap(0, 398, Short.MAX_VALUE)
                .addComponent(ScrollBarCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FrameCuentasLayout.setVerticalGroup(
            FrameCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollBarCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );

        getContentPane().add(FrameCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 420, 300));

        BotonVolver.setBackground(new java.awt.Color(0, 0, 102));
        BotonVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonVolver.setForeground(new java.awt.Color(255, 255, 255));
        BotonVolver.setText("Volver");
        getContentPane().add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Configuración");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpeg"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Banco banco = new Banco();
                banco.cargarClientes("clientes.xml");
                
                String idUsuario = "1";

                // Busca al cliente por la identificación
                Cliente cliente = banco.buscarClientePorID(idUsuario);

                if (cliente != null) {
                    // Si el cliente se encuentra, obtenemos su identificación y cargamos la interfaz.
                    String identificacion = cliente.getIdentificacion();
                    new InterfazCliente(banco, cliente, identificacion).setVisible(true);
                } else {
                    System.out.println("Cliente no encontrado.");
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVolver;
    private javax.swing.JInternalFrame FrameCuentas;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JScrollBar ScrollBarCuentas;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
