/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Banco;
import GUI.IniciarSesion;
import GUI.RegistrarCliente;
import GUI.ValidarIdCliente;
/**
 *
 * @author Estudiante
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final Banco banco;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Banco banco) {
        initComponents();
        this.setLocationRelativeTo(null);
        banco = new Banco();
        banco.cargarClientes("clientes.xml");
        this.banco = banco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        AgregarCuenta = new javax.swing.JButton();
        IniciarSesion = new javax.swing.JButton();
        Registrarse = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        JLabelFondo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarCuenta.setBackground(new java.awt.Color(0, 153, 204));
        AgregarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCuenta.setText("Agregar cuenta");
        AgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, 50));

        IniciarSesion.setBackground(new java.awt.Color(0, 153, 204));
        IniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesion.setText("Iniciar sesión");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 120, 50));

        Registrarse.setBackground(new java.awt.Color(0, 153, 204));
        Registrarse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registrarse.setForeground(new java.awt.Color(255, 255, 255));
        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 110, 50));

        Salir.setBackground(new java.awt.Color(0, 153, 204));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBanco.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 490, 270));

        JLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpeg"))); // NOI18N
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        this.setVisible(false);
        IniciarSesion iniciarSesion = new IniciarSesion(this);
        iniciarSesion.setVisible(true);
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        this.setVisible(false);
        RegistrarCliente registrarCliente = new RegistrarCliente(this, banco); // Pasar el objeto banco
        registrarCliente.setVisible(true); 
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void AgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCuentaActionPerformed
        ValidarIdCliente referencia = new ValidarIdCliente(this);
        referencia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarCuentaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Banco banco = new Banco();
                banco.cargarClientes("clientes.xml");
                new MenuPrincipal(banco).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCuenta;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Registrarse;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
